### ISSUE TITLE
Fix case-sensitivity in menu links

### ISSUE THREAD

**Issue by afred** [PBCore-AV-Metadata/pbcore-av-metadata.github.io#1]
URLs appear to be case sensitive, and some of the menu links to elements are lining to pages that don't exist because of incorrect capitalization.

**Done when:** menu links to the following pages are fixed:
  1. menu URL "elements/pbcoreInstantiation", actual URL "elements/pbcoreinstantiation"
  1. menu URL "elements/instantiationtracks", actual URL "elements/instantiationTracks"

**Comment by sroosa** [comment]
Closed by #21
