### ISSUE TITLE
code blocks seem to be shown on one line when rendered

### ISSUE THREAD

**Issue by dericed** [PBCore-AV-Metadata/pbcore-av-metadata.github.io#14]
There's a few examples of code blocks using this....

~~~
```
echo hey this
echo is code
```
~~~

...style of code blocking, as in https://github.com/dericed/pbcore-av-metadata.github.io/blame/master/_posts/2018-11-28-pbcore-audiovisual-tricks.md#L66-L69. But in the rendered output it is show as

```
echo hey thisecho is code
```

so boo

**Comment by sroosa** [comment]
Closed by #21
