### ISSUE TITLE
Controlled Vocab pages show URIs

### ISSUE THREAD

**Issue by sroosa** [PBCore-AV-Metadata/pbcore-av-metadata.github.io#26]
Some people coming to the website will just want to know the URI for a specific term, and rather than making them go to the OMR, we can also show those on our website, term by term. 

Done when:
- [x] individual vocab files have uris included
- [x] each page displays a list of terms, definitions, and uris that looks something like:
Term
Definition: [text of definition]
URI: [uri value]

**Comment by foglabs** [comment]
Added URIs for vocabs like this:

![screen shot 2019-01-14 at 9 52 31 am](https://user-images.githubusercontent.com/8140840/51119979-1f7f6080-17e2-11e9-9807-4e4a4f2eda7c.png)

**Comment by sroosa** [comment]
Closed by #42
