### ISSUE TITLE
Add a browse by keyword index section

### ISSUE THREAD

**Issue by sroosa** [PBCore-AV-Metadata/pbcore-av-metadata.github.io#28]
Like: http://samvera.github.io/browse_pages.html

I believe they use a custom plugin to do this, so let's use that too. 

- [x] add keywords to front matter of all pages
- [x] Add page for browsing by keyword at /browse
- [x] Add link to /browse on the right side of the header, next to where the search bar will also be.

**Comment by foglabs** [comment]
dropped in the plugin - we will still need to add the keywords in order to fully populate the browse_pages page

**Comment by sroosa** [comment]
Closed by #46
