### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by sroosa** [PBCore-AV-Metadata/pbcore-av-metadata.github.io#29]
Add a search bar (like in the designs) and have that render the search results using a google custom search. For now we don't need to style the search results, they can just look like Google search results.

**Comment by sroosa** [comment]
We need a gmail account to set up a custom search, so looking into creating a new one for pbcore.

**Comment by foglabs** [comment]
Added search.

**Comment by sroosa** [comment]
Additional comments: Some indication that this is searching specifically the pbcore site
we don't want it to search v1, etc.

**Comment by sroosa** [comment]
Closed by #56
