### ISSUE TITLE
PBCore Cataloging Tool Page

### ISSUE THREAD

**Issue by sroosa** [PBCore-AV-Metadata/pbcore-av-metadata.github.io#36]
- [x] have the width of the download buttons for Mac and PC be the same. Sometimes it shows that way now, and sometimes it doesn't (maybe dependent on screenwidth)
- [x] Make the left and right buttons on the gallery more visible (change the color, or add some kind of background color?)
- [ ] Move the captions in the gallery to above the images ( check how this looks before committing)

**Comment by foglabs** [comment]
how about this?

![screen shot 2019-01-11 at 12 44 32 pm](https://user-images.githubusercontent.com/8140840/51050399-ae03a000-159e-11e9-9e0d-5db0ddb20db7.png)

**Comment by sroosa** [comment]
@foglabs can you make them a little bit smaller, and the background color a little lighter and more transparent?

**Comment by foglabs** [comment]
yes! right side arrow shows what the hover state for the arrows

![screen shot 2019-01-11 at 1 05 28 pm](https://user-images.githubusercontent.com/8140840/51051373-9d085e00-15a1-11e9-85d0-60d434a39390.png)

**Comment by sroosa** [comment]
I think we should leave the captions below. It's where people look for them, and it's where Bootstrap wants to put them.

**Comment by sroosa** [comment]
Closed by #39
