### ISSUE TITLE
Update text size and weight to match designs

### ISSUE THREAD

**Issue by sroosa** [PBCore-AV-Metadata/pbcore-av-metadata.github.io#38]
- [x] homepage has some boldness and size discrepancies with the designs (both headers and text need to be larger and less bold in some cases)
- [x] Check if headers and body text on subpages should be bold or not based on the designs
- [x] Text on the FAQ page within each question looks to be a little lighter/less bold than the headers in the mockup. For example, see page 10 of the attached mockups. There is some text that is bolded in the Answer to a question and the rest of the text is lighter/less bold.

**Comment by foglabs** [comment]
@sroosa Working on these

**Comment by sroosa** [comment]
Closed by #39
